title: Voice of Data
description: Janice Whitson — Clarity. Empathy. Understanding.
theme: jekyll-theme-minimal


contact:
  title: "Let’s talk"
  email: "janice.whitson.1@outlook.com"
  linkedin: "https://www.linkedin.com/in/janice-whitson-aa2a632/"
