title: Voice of Data
description: Janice Whitson |
  <span>Clarity. Empathy. Understanding.</span>
theme: jekyll-theme-minimal


contact:
  title: "Letâ€™s talk"
  email: "janice.whitson.1@outlook.com"
  linkedin: "https://www.linkedin.com/in/janice-whitson-aa2a632/"
